# shellcheck shell=sh
# Shared helpers, sourced from the repository root.

require_root() {
	[ "$(id -u)" -eq 0 ] || { echo "run as root (sudo)" >&2; exit 1; }
}

# Man page and shell completions generated by recoil16ctl: install_ctl_extras <binary> <share dir>
install_ctl_extras() {
	mkdir -p "$2/man/man1" "$2/bash-completion/completions" "$2/zsh/site-functions" "$2/fish/vendor_completions.d"
	"$1" man "$2/man/man1"
	"$1" completions bash > "$2/bash-completion/completions/recoil16ctl"
	"$1" completions zsh > "$2/zsh/site-functions/_recoil16ctl"
	"$1" completions fish > "$2/fish/vendor_completions.d/recoil16ctl.fish"
}

remove_ctl_extras() {
	rm -f "$1"/man/man1/recoil16ctl*.1 "$1/bash-completion/completions/recoil16ctl" \
	      "$1/zsh/site-functions/_recoil16ctl" "$1/fish/vendor_completions.d/recoil16ctl.fish"
}
